"""
CDS Hooks service for MEDGRAPH.

Implements the CDS Hooks specification (https://cds-hooks.org/) for
drug interaction checking at order entry time.

EDUCATIONAL DISCLAIMER: All CDS cards generated by this service are
for informational/educational purposes only. They do not constitute
clinical decision support, medical advice, or professional judgment.
Always defer to licensed healthcare professionals.
"""

from __future__ import annotations

import logging
import uuid
from typing import Any

import networkx as nx

from medgraph.engine.analyzer import CascadeAnalyzer
from medgraph.engine.models import DrugInteractionResult
from medgraph.fhir.models import CDSCard, CDSRequest, CDSResponse, CDSServiceDefinition
from medgraph.fhir.parser import FHIRParser
from medgraph.graph.store import GraphStore

logger = logging.getLogger(__name__)

_SOURCE = {
    "label": "MEDGRAPH Drug Interaction Analyzer",
    "url": "https://github.com/HieuNTg/medgraph",
}

# Severity -> CDS indicator mapping
_SEVERITY_TO_INDICATOR = {
    "critical": "critical",
    "major": "warning",
    "moderate": "info",
    "minor": "info",
}


class CDSHooksService:
    """
    CDS Hooks service implementing order-select hook for drug interaction checking.

    All cards produced carry educational framing and are NOT prescriptive.
    """

    MEDICAL_DISCLAIMER = (
        "FOR INFORMATIONAL PURPOSES ONLY. "
        "This information is educational and does not replace clinical judgment. "
        "Consult a licensed pharmacist or prescriber before making any medication decisions."
    )

    def __init__(self, store: GraphStore, graph: nx.DiGraph) -> None:
        self.store = store
        self.graph = graph
        self.parser = FHIRParser(store)
        self._analyzer = CascadeAnalyzer()

    def get_services(self) -> list[dict]:
        """CDS Hooks discovery endpoint — returns service definitions."""
        service = CDSServiceDefinition(
            hook="order-select",
            title="MEDGRAPH Drug Interaction Checker",
            description=(
                "Educational drug interaction cascade analysis. "
                "Identifies potential pharmacokinetic and pharmacodynamic interactions "
                "across ordered medications. FOR INFORMATIONAL PURPOSES ONLY."
            ),
            id="medgraph-order-select",
            prefetch={
                "patientMedications": (
                    "MedicationRequest?patient={{context.patientId}}"
                    "&status=active"
                ),
            },
        )
        return [service.model_dump()]

    def handle_order_select(self, request: CDSRequest) -> CDSResponse:
        """
        Handle order-select CDS hook request.

        Steps:
          1. Collect drug IDs from context (draftOrders) + prefetch (patientMedications)
          2. Run CascadeAnalyzer
          3. Convert interactions to educational CDS cards
        """
        drug_ids: list[str] = []

        # Parse draftOrders from hook context
        draft_orders = request.context.get("draftOrders", {})
        if draft_orders:
            drug_ids.extend(self.parser.extract_drug_ids(draft_orders))

        # Parse existing patient medications from prefetch
        patient_meds = request.prefetch.get("patientMedications", {})
        if patient_meds:
            drug_ids.extend(self.parser.extract_drug_ids(patient_meds))

        # Deduplicate preserving order
        seen: set[str] = set()
        unique_ids: list[str] = []
        for did in drug_ids:
            if did not in seen:
                seen.add(did)
                unique_ids.append(did)

        if len(unique_ids) < 2:
            # Not enough resolved drugs to check interactions
            return CDSResponse(cards=[])

        try:
            report = self._analyzer.analyze(unique_ids, self.graph, self.store)
        except Exception as exc:
            logger.error("CDSHooksService: analysis failed: %s", exc)
            return CDSResponse(cards=[])

        cards: list[CDSCard] = []
        for interaction in report.interactions:
            # Only surface moderate+ severity to avoid alert fatigue
            if interaction.severity in ("minor",) and interaction.risk_score < 0.3:
                continue
            card = self._interaction_to_card(interaction)
            cards.append(card)

        # Deduplicate disclaimer card only if there are interaction cards
        if cards:
            cards.append(self._disclaimer_card())

        return CDSResponse(cards=cards)

    def _interaction_to_card(self, interaction: DrugInteractionResult) -> CDSCard:
        """
        Map a MEDGRAPH DrugInteractionResult to a CDS card.

        Indicator mapping:
          critical -> "critical"
          major    -> "warning"
          moderate/minor -> "info"

        All cards use educational framing — never prescriptive language.
        """
        indicator = _SEVERITY_TO_INDICATOR.get(interaction.severity, "info")
        drug_a = interaction.drug_a.name
        drug_b = interaction.drug_b.name

        summary = (
            f"[Educational] Potential {interaction.severity.upper()} interaction: "
            f"{drug_a} + {drug_b}"
        )

        # Build detail from direct interaction data
        detail_parts: list[str] = [
            f"**Educational information only — not clinical advice.**",
            "",
        ]

        direct = interaction.direct_interaction
        if direct and direct.description:
            detail_parts.append(direct.description)
        if direct and direct.mechanism:
            detail_parts.append(f"_Mechanism:_ {direct.mechanism}")

        if interaction.cascade_paths:
            enzymes = set()
            for path in interaction.cascade_paths[:3]:
                for step in path.steps:
                    if "enzyme" in step.relation.lower() or step.relation in (
                        "inhibits", "induces", "metabolized_by"
                    ):
                        enzymes.add(step.target)
            if enzymes:
                detail_parts.append(f"_Involved enzymes:_ {', '.join(sorted(enzymes))}")

        detail_parts.extend([
            "",
            f"_Risk score:_ {interaction.risk_score:.2f}",
            "",
            self.MEDICAL_DISCLAIMER,
        ])

        return CDSCard(
            uuid=str(uuid.uuid4()),
            summary=summary,
            detail="\n".join(detail_parts),
            indicator=indicator,
            source=_SOURCE,
            suggestions=[],
        )

    def _disclaimer_card(self) -> CDSCard:
        """Standalone educational disclaimer card appended to all responses."""
        return CDSCard(
            uuid=str(uuid.uuid4()),
            summary="[Educational] MEDGRAPH — Informational Use Only",
            detail=self.MEDICAL_DISCLAIMER,
            indicator="info",
            source=_SOURCE,
        )
